### ISSUE TITLE
Agregar cantidad de tiempo de hornear

### ISSUE THREAD

**Issue by desagrupoweb** [desagrupoweb/prueba#14]
Especificar el tiempo que se debe hornear en minutos

**Comment by soportegrupowebx** [comment]
vale, yo hago esa parte.

**Comment by soportegrupowebx** [comment]
voy a cambiar el tiempo de horneado a 5 minutos, ya que la prueba que hice de a los 10 minutos el pan se medio quemó.

**Comment by desagrupoweb** [comment]
ok continua
